version: '3'
services:
  auth:
    build: .
    ports:
     - "8080:8080"
    environment:
     - MONGODB_URI=mongodb://xeroqueo:x3r0qu30@ds111244.mlab.com:11244/auth
    volumes:
     - .:/starter
     - /starter/node_modules
     
