apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auth
  namespace: api
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  tls:
    - hosts:
        - api.xeroqueo.com.br
      secretName: api-tls
  rules:
    - host: api.xeroqueo.com.br
      http:
        paths:
          - path: /accountservice/
            backend:
              serviceName: auth
              servicePort: 8080
